// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_usmc_desert_support_ryan");
	self attach("head_hero_ghost_forest", "", 1);
	self.headModel = "head_hero_ghost_forest";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_usmc_desert_support_ryan");
	precacheModel("head_hero_ghost_forest");
}
